version: "3"
services:
  app:
    container_name: app
    restart: always
    build: app/
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    build: db/
    volumes:
      - ./db/data:/data/db
    ports:
      - "27017:27017"